### ISSUE TITLE
Middle Click Does Not Work

### ISSUE THREAD

**Issue by Daniel-Patino** [NewbieOrange/clicksort#7] opened 2021-12-09 14:38 UTC
Middle Click to Sort does not work. I made sure I was in middle-click mode. For some reason the double-click mode still works.

**Comment by NewbieOrange** [comment] 2021-12-09 15:52
What version of Clicksort and Bukkit are you using? Also some plugins may interfere with middle-clicks, please try again without any plugin.

**Comment by NewbieOrange** [comment] 2021-12-15 15:46
If you are using 1.18, this is a duplicate of #9, please continue discussion there.

**Closed as completed by NewbieOrange** 2021-12-15 15:46 UTC
Labels: duplicate
