### ISSUE TITLE
Middle click sort does not work in 1.18

### ISSUE THREAD

**Issue by wiiwas** [NewbieOrange/clicksort#9] opened 2021-12-14 12:11 UTC
only thing that works is changing sorting mode. actual sorting with middle click doesnt.

**Comment by NewbieOrange** [comment] 2021-12-15 15:07
Apparently mojang decided that sending middle click to server in survival mode is a _bug_ and "fixed" the issue.

See https://bugs.mojang.com/browse/MC-46584

**Comment by NewbieOrange** [comment] 2021-12-15 15:22
It is possible for us to use the swap-offhand key (defaults to F) in inventory for sorting, is that preferable?

**Comment by NewbieOrange** [comment] 2021-12-15 16:03
Swap-key sorting has been added in v1.5.1 and can be downloaded from GitHub releases or dev.bukkit.org.

This issue will be kept open for a while for suggestions and inputs on the new click method.

**Comment by ribbiks** [comment] 2021-12-16 17:01
Greetings! I was testing out the swap-key sort and it seems to have an issue in that it causes your offhand item to briefly disappear (and will reappear in your inventory if you subsequently click somewhere). E.g. each use of sort was unequipping shield.

**Comment by NewbieOrange** [comment] 2021-12-17 03:13
Confirmed, trying to find a fix for this.

**Comment by NewbieOrange** [comment] 2021-12-18 06:09
@ribbiks please try the latest version

**Comment by ribbiks** [comment] 2021-12-18 19:50
I just tested 1.5.2 and swap-sort seems to work correctly now when sorting personal inventory (shield stays equipped), but it still disappears for me when sorting chests.

**Comment by NewbieOrange** [comment] 2021-12-19 02:36
@ribbiks Hi, the issue is from a client-side bug. I have added the workaround for it, please redownload 1.5.2.

**Comment by ribbiks** [comment] 2021-12-19 03:04
I redownloaded and it seems to be working great now. Thanks for your work on this!

**Comment by NewbieOrange** [comment] 2021-12-19 14:46
Glad its working great for you! Please consider give this project a star if you find it useful 😃.

**Closed as completed by NewbieOrange** 2021-12-19 14:46 UTC
Labels: enhancement

**Comment by Kuuchuu** [comment] 2022-03-13 09:36
@NewbieOrange You may want to add this to the plugin's description page. I figured that sorting option was just broken as I wasn't aware what the "swap" key was and the plugin description only states that middle mouse is used (along with the other modes). Letting people know that the "F" key instead of middle mouse sorts when on swap mode may be helpful. Thanks for the great plugin, I appreciate your work on it.

**Comment by NewbieOrange** [comment] 2022-03-13 10:46
> @NewbieOrange You may want to add this to the plugin's description page. I figured that sorting option was just broken as I wasn't aware what the "swap" key was and the plugin description only states that middle mouse is used (along with the other modes). Letting people know that the "F" key instead of middle mouse sorts when on swap mode may be helpful. Thanks for the great plugin, I appreciate your work on it.

Sure! I forgot to update the description. Thanks for the feedback!
